### PR TITLE
S meter fixes

### PR DESCRIPTION
**Pull request by SigmazGFX**
Changed the way that the rx_gain value is shared between sbitx.c and sbitx_gtk.c Because rx_gain is a static int it cannot be shared directly outside of sbitx.c so I put in a getter function int get_rx_gain(void); to retrieve the value and ship it over to the display function.
Also adjusted the SCALING_TRIM to get the s-meter close to local observations on another rig.

### CODE REVIEW

**Review by Mashintime — APPROVED** [review]
Looks good to me

**Comment by drexjj** [comment]
If this from the s-meter branch, then there are some issues still present..

\smeter_option does not work from the text menu

The IF gain still changes the s-meter sensitivity giving false feedback.

**Comment by SigmazGFX** [comment]
I’ll close the PR and see about getting the Log function spruced up.
The command is \smeteropt on|off

**Comment by SigmazGFX** [comment]
I’ll close the PR and see about getting the Log function spruced up.
The command is \smeteropt on|off

**Pull request closed without merging**
