### PR TITLE
Generate optimized binary

### PR DESCRIPTION
**Pull request by Mashintime**
Generate and use an optimized binary, while also building a debug binary for testing.  

Saw about 1% less cpu usage in a quick test.

### CODE REVIEW

**Comment by drexjj** [comment]
Thanks. I will check this out.

**Comment by drexjj** [comment]
Building debug binary
Building opimized binary
sbitx_gtk.c: In function ‘do_tuning’:
sbitx_gtk.c:2709:30: warning: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
 2709 |                         if (!strcmp(get_field("#rit")->value, "ON")){
      |                              ^
sbitx_gtk.c:2725:30: warning: ‘strcmp’ reading 1 or more bytes from a region of size 0 [-Wstringop-overread]
 2725 |                         if (!strcmp(get_field("#rit")->value, "ON")){
      |                              ^

**Comment by Mashintime** [comment]
I'm not really a C guy, I got the same messages, but still seems to run fine.

**Comment by Mashintime** [comment]
Did some further research and seems to be a false positive warning.  I was able to rewrite the code to copy the value of get_field("#rit")->value to a new string and then use the new variable in the if block that throws the error, and the error goes away.  But that is ineffieceint in my eyes.  If this is of any value in your opinion, happy to re-engage to meet your standards.

**Comment by drexjj** [comment]
Sure. Send over the code replacement and I will take a look. Thank you!

**Comment by Mashintime** [comment]
My fix after syncing resulted in the messages coming back.  I believe it's a false positive as the following lines would also get flagged as they are doing the exact same thing, and the Warning is enabled by default, so it should popup regardless of using -O or not.

https://github.com/drexjj/sbitx/blob/1414ce4adad12e64ef43bad4eab2f97c8876dac2/sbitx_gtk.c#L1158

https://github.com/drexjj/sbitx/blob/1414ce4adad12e64ef43bad4eab2f97c8876dac2/sbitx_gtk.c#L2684

https://github.com/drexjj/sbitx/blob/1414ce4adad12e64ef43bad4eab2f97c8876dac2/sbitx_gtk.c#L3197

https://github.com/drexjj/sbitx/blob/1414ce4adad12e64ef43bad4eab2f97c8876dac2/sbitx_gtk.c#L3203

https://github.com/drexjj/sbitx/blob/1414ce4adad12e64ef43bad4eab2f97c8876dac2/sbitx_gtk.c#L4152

https://github.com/drexjj/sbitx/blob/1414ce4adad12e64ef43bad4eab2f97c8876dac2/sbitx_gtk.c#L4595

I think we could do one of these:

- Switch to just -O1 (doesn't seem to pop up for me using O1, but O2/O3 provide more optimizations)
- Leave it at -O3 and ignore the warnings
- Leave it as -O3 and add the flag to not print the warning (-Wno-stringop-overread, but could suppress future real warnings)
- Do nothing, although I think it's important to use an optimized binary if at all possible.

**Comment by Mashintime** [comment]
Or another option, just leave the build script alone and introduce another script. i.e. build-optimized or what not.

**Comment by drexjj** [comment]
Sounds good. I tested with a few different compiler flags as well. 03 seems to optimize it quite a lot.  02 yields the same results. I referenced this when testing.   https://interrupt.memfault.com/blog/code-size-optimization-gcc-flags

**Pull request closed without merging**
